jacket/urls.py
from django.urls import path
from . import views

app_name = 'jacket'

urlpatterns = [
    path('', views.JacketIndex.as_view(), name='index'),
    path('<int:pk>/', views.JacketDetails.as_view(), name='details'),
    path('create/', views.JacketCreate.as_view(), name='create'),
    path('search/', views.search_results, name='search'),
    path('return/<int:jacket_id>/', views.mark_returned, name='return'),
    path('claim/<int:jacket_id>/', views.claim_jacket, name='claim'),
]

jacketswap/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('about/', TemplateView.as_view(template_name='generic/about.html'), name='about'),
    path('user/', include('user.urls')),
    path('jacket/', include('jacket.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
from jacket import views as jacket_views

app_name = 'user'

urlpatterns = [
    path('register/', views.RegisterFormView.as_view(), name='register'),
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('jackets/', jacket_views.your_jackets, name='jackets')
]

jacketswap/views.py
from django.shortcuts import redirect, render
from django.views.generic import View
from jacket.models import Jacket


class IndexView(View):

    def get(self, request):
        jackets_list = Jacket.objects.all().order_by('-added_on')[:10]
        return render(request, 'generic/index.html', {'jackets': jackets_list})

jacketswap/templates/generic/about.html
{% extends "generic/base.html" %}

{% block title %}About &middot; JacketSwap{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <h5>About JacketSwap</h5>
        <p>
            You have been at a night club for a great night out with your friends. When you decide to go home and fetch
            your jacket, you come to the realisation that it is gone. Someone must have grabbed it, either by mistake or
            because their jacket was also stolen. JacketSwap is created to return these jackets to their rightful
            owners.
        </p>
        <p>
            JacketSwap is only created as a mediating service towards victims of jacket theft. JacketSwap cannot be held
            accountable for the actions performed by the users on the site. None of the items on the website are
            possession of the JacketSwap organisation.
        </p>
    </div>
{% endblock %}

jacketswap/templates/generic/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load staticfiles %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

        <title>{% block title %}JacketSwap{% endblock %}</title>

        <link rel="shortcut icon" href="{% static "generic/img/favicon.ico" %}" type="image/x-icon">
        <link rel="icon" href="{% static "generic/img/favicon.ico" %}" type="image/x-icon">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
         <link href="https://fonts.googleapis.com/css?family=Quicksand:400,500,700" rel="stylesheet">
        {% block stylesheets %}
            <link rel="stylesheet" href="{% static "generic/css/variables.css" %}" type="text/css">
            <link rel="stylesheet" href="{% static "generic/css/base.css" %}" type="text/css">
        {% endblock %}
    </head>
    <body>
        <div class="container">
            <div class="row wrapper">
                <div class="col-lg-12 main">
                    {% block navigation %}
                        <div class="header-nav" style="background-image: url({% static 'generic/img/splash.jpg' %})">
                            <a href="{% url 'index' %}">
                                <div class="logo">
                                    <img src="{% static 'generic/img/js-logo-white-37x37.png' %}" alt="JacketSwap logo" />
                                    <span>JacketSwap</span>
                                </div>
                            </a>
                            <nav class="splash-navigation">
                                {% include 'generic/navigation.html' %}
                                <div class="hamburger">
                                    <i class="fas fa-bars"></i>
                                </div>
                            </nav>
                        </div>
                        <div class="mobile-navigation">
                            {% include 'generic/navigation.html' %}
                        </div>
                    {% endblock %}
                    <div class="content">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>

        {% block scripts %}
            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
            <script src="https://use.fontawesome.com/releases/v5.0.1/js/all.js"></script>
            <script src="{% static "generic/js/base.js" %}"></script>
        {% endblock %}
    </body>
</html>

jacketswap/templates/generic/form.html
{% for field in form %}
    <div class="form-group">
        <label for="{{ field.auto_id }}" class="control-label">
            {{ field.label }}
        </label>
        {% if field.field.widget.input_type == "file" %}
            <div class="file-input">
                <span class="select-file-string">Select file</span>
                <span class="selected-file"></span>
        {% endif %}
        {{ field }}
        {% if field.field.widget.input_type == "file" %}
                <i class="fas fa-check file-selected"></i>
            </div>
        {% endif %}
    </div>
{% endfor %}

jacketswap/templates/generic/index.html
{% extends 'generic/base.html' %}
{% load staticfiles %}

{% block title %}Home &middot; JacketSwap{% endblock %}

{% block navigation %}
    <div class="mobile-navigation">
        {% include 'generic/navigation.html' %}
    </div>
    <div class="splash" style="background-image: url({% static 'generic/img/splash.jpg' %})">
        <nav class="splash-navigation">
            {% include 'generic/navigation.html' %}
            <div class="hamburger">
                <i class="fas fa-bars"></i>
            </div>
        </nav>
        <div class="logo">
            <img src="{% static 'generic/img/js-logo-white.png' %}" alt="JacketSwap logo" />
            <h1>JacketSwap</h1>
            <form action="{% url 'jacket:search' %}" method="post">
                {% csrf_token %}
                <input class="js-input-splash" type="text" name="search" placeholder="Search (ex. black jacket in Fuik)">
            </form>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <h5>Recently added jackets</h5>
        {% for jacket in jackets %}
            <a href="{% url 'jacket:details' jacket.pk %}">
                <div class="jacket-item {% if jacket.returned %}returned{% endif %}">
                    <div class="image" style="background-image: url({{ jacket.image.url }})"></div>
                    <div class="info">
                        <div class="title">{{ jacket.title }}</div>
                        <div class="location">{{ jacket.location }}</div>
                    </div>
                    <div class="lof">
                        {% if jacket.returned %}
                            Returned!
                        {% else %}
                            {{ jacket.lost_found }}
                        {% endif %}
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

jacketswap/templates/generic/navigation.html
{% load staticfiles %}

<ul>
    <a href="{% url 'about' %}"><li>About</li></a>
    {% if user.is_authenticated %}
        <a href="#"><li id="user-navigation">{{ user.username }} <i class="fas fa-caret-down"></i></li></a>
        <div class="user-menu">
            <ul>
                <a href="{% url 'user:jackets' %}"><li>Your jackets</li></a>
                <a href="{% url 'user:logout' %}"><li>Logout</li></a>
            </ul>
        </div>
        <ul class="mobile-user-menu">
            <a href="{% url 'user:jackets' %}"><li>Your jackets</li></a>
            <a href="{% url 'user:logout' %}"><li>Logout</li></a>
        </ul>
    {% else %}
        <a href="{% url 'user:login' %}"><li>Login</li></a>
    {% endif %}
    <a href="{% url 'jacket:create' %}"><li class="button">Add jacket</li></a>
</ul>