jacketswap/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('about/', TemplateView.as_view(template_name='generic/about.html'), name='about'),
    path('user/', include('user.urls')),
    path('jacket/', include('jacket.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
from jacket import views as jacket_views

app_name = 'user'

urlpatterns = [
    path('register/', views.RegisterFormView.as_view(), name='register'),
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('jackets/', jacket_views.your_jackets, name='jackets')
]

user/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.FileField()

user/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django import forms


class RegisterForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control js-input'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control js-input'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control js-input'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control js-input'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control js-input'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password']


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control js-input'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control js-input'}))

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")

        user = authenticate(username=username, password=password)

        if user is None:
            raise forms.ValidationError("Wrong username and password combination.")
        if not user.is_active:
            raise forms.ValidationError("Your account is not active.")

        return self.cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password']

jacketswap/views.py
from django.shortcuts import redirect, render
from django.views.generic import View
from jacket.models import Jacket


class IndexView(View):

    def get(self, request):
        jackets_list = Jacket.objects.all().order_by('-added_on')[:10]
        return render(request, 'generic/index.html', {'jackets': jackets_list})

user/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import View
from .forms import RegisterForm, LoginForm


class RegisterFormView(View):
    form_class = RegisterForm
    template_name = 'user/register.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user.username = username
            user.set_password(password)

            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('index')

        # Form not valid/user not authenticated/user not active
        return render(request, self.template_name, {'form': form})


class LoginFormView(View):
    form_class = LoginForm
    template_name = 'user/login.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('index')

        # Form not valid/user not authenticated/user not active
        return render(request, self.template_name, {'form': form})


def user_logout(request):
    logout(request)
    return redirect('index')

jacketswap/templates/user/login.html
{% extends "generic/base.html" %}

{% block title %}Log in &middot; JacketSwap{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <h5>User login</h5>
        {{ form.non_field_errors }}
        <form class="form-vertical" action="{% url "user:login" %}" method="post">
            {% csrf_token %}
            {% include "generic/form.html" %}
            <div class="form-buttons">
                <button type="submit" class="btn button-primary">Log in</button>
                <a href="{% url "user:register" %}">
                    <button type="button" class="btn button-secondary button-margin">Register</button>
                </a>
            </div>
        </form>
    </div>
{% endblock %}

jacketswap/templates/user/register.html
{% extends "generic/base.html" %}

{% block title %}Register &middot; JacketSwap{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <h5>User registration</h5>
        <form class="form-vertical" action="{% url "user:register" %}" method="post">
            {% csrf_token %}
            {% include "generic/form.html" %}
            <div class="form-buttons">
                <button type="submit" class="btn button-primary">Submit</button>
            </div>
        </form>
    </div>
{% endblock %}