jacket/urls.py
from django.urls import path
from . import views

app_name = 'jacket'

urlpatterns = [
    path('', views.JacketIndex.as_view(), name='index'),
    path('<int:pk>/', views.JacketDetails.as_view(), name='details'),
    path('create/', views.JacketCreate.as_view(), name='create'),
    path('search/', views.search_results, name='search'),
    path('return/<int:jacket_id>/', views.mark_returned, name='return'),
    path('claim/<int:jacket_id>/', views.claim_jacket, name='claim'),
]

jacketswap/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('about/', TemplateView.as_view(template_name='generic/about.html'), name='about'),
    path('user/', include('user.urls')),
    path('jacket/', include('jacket.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
from jacket import views as jacket_views

app_name = 'user'

urlpatterns = [
    path('register/', views.RegisterFormView.as_view(), name='register'),
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('jackets/', jacket_views.your_jackets, name='jackets')
]

jacket/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Jacket(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField()
    location = models.CharField(max_length=300)
    image = models.FileField(default='generic/img/series-placeholder.png')
    added_by = models.ForeignKey(User, default='1', on_delete=models.CASCADE)
    added_on = models.DateTimeField(auto_now_add=True)
    returned = models.BooleanField(default=False)
    lost_found = models.CharField(default='found', max_length=5)

    def get_absolute_url(self):
        return reverse('jacket:details', kwargs={'pk': self.pk})

    def __str__(self):
        return '"' + self.title + '" in "' + self.location + '"'

jacket/forms.py
from django import forms
from .models import Jacket


class CreateJacketForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control js-input'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control js-input'}))
    location = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control js-input'}))
    image = forms.FileField(widget=forms.FileInput(attrs={'class': 'form-control js-input file-input'}))
    lost_found = forms.ChoiceField(choices={('lost', 'Lost'), ('found', 'Found')},
                                   widget=forms.RadioSelect(attrs={'class': 'radio-select'}),
                                   label="Lost or found",
                                   initial='lost')

    class Meta:
        model = Jacket
        fields = ['title', 'description', 'location', 'image', 'lost_found']

jacket/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.core.mail import send_mail
from django.urls import reverse
from django.views import generic
from simple_search import search_filter
from .models import Jacket
from .forms import CreateJacketForm


class JacketIndex(generic.ListView):
    template_name = 'jacket/index.html'

    jackets_list = Jacket.objects.all()

    def get_queryset(self):
        return self.jackets_list

    def get_context_data(self, **kwargs):
        context = super(JacketIndex, self).get_context_data(**kwargs)
        # Possible add to context by using context['item'] = item here
        return context


class JacketDetails(generic.DetailView):
    template_name = 'jacket/details.html'
    model = Jacket

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Possible add to context by using context['item'] = item here
        return context


class JacketCreate(generic.CreateView):
    form_class = CreateJacketForm
    template_name = 'jacket/create.html'
    model = Jacket

    def form_valid(self, form):
        form.instance.added_by = self.request.user
        form.save()
        return super().form_valid(form)


def search_results(request):
    template_name = "jacket/index.html"

    if request.method == 'POST':
        search_string = request.POST['search']
        if search_string == '':
            context = {'jackets': Jacket.objects.all().order_by('-added_on'), 'source': 'search'}
            return render(request, template_name, context)
        search_fields = ['title', 'description', 'location']
        f = search_filter(search_fields, search_string)
        context = {'jackets': Jacket.objects.filter(f).order_by('-added_on'), 'source': 'search'}
        return render(request, template_name, context)
    else:
        context = {'jackets': Jacket.objects.all().order_by('-added_on'), 'source': 'search'}
        return render(request, template_name, context)


def your_jackets(request):
    if request.user.is_authenticated:
        template_name = "jacket/index.html"
        user_jackets = Jacket.objects.filter(added_by_id=request.user.id)
        return render(request, template_name, {'jackets': user_jackets, 'source': 'your-jackets'})
    else:
        return redirect('index')


def mark_returned(request, jacket_id):
    jacket = get_object_or_404(Jacket, pk=jacket_id)
    if request.user.is_authenticated and request.user.pk == jacket.added_by_id:
        jacket.returned = False if jacket.returned is True else True
        jacket.save()
        return redirect('jacket:details', pk=jacket_id)
    else:
        return redirect('index')


def claim_jacket(request, jacket_id):
    user = request.user
    jacket = get_object_or_404(Jacket, pk=jacket_id)
    subject = 'New response on JacketSwap!'
    message = 'Dear ' + jacket.added_by.username + ',\n\nJacketSwap user ' + user.username + ' responded to your jacket post on JacketSwap.\nCheck out your post here: ' + request.build_absolute_uri(reverse('jacket:details', args=[jacket_id])) + '\nYou can contact ' + user.username + ' by sending an e-mail to: ' + user.email + '\n\nKind regards,\n\nJacketSwap'
    from_email = settings.EMAIL_HOST_USER
    send_mail(subject, message, from_email, ['standerksen@outlook.com', user.email], fail_silently=False)

    return render(request, 'jacket/claimed.html', {'jacket': jacket})

jacketswap/views.py
from django.shortcuts import redirect, render
from django.views.generic import View
from jacket.models import Jacket


class IndexView(View):

    def get(self, request):
        jackets_list = Jacket.objects.all().order_by('-added_on')[:10]
        return render(request, 'generic/index.html', {'jackets': jackets_list})

jacketswap/templates/jacket/claimed.html
{% extends "generic/base.html" %}

{% block title %}About &middot; JacketSwap{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <h5>Success</h5>
        <p>
            You have successfully sent an e-mail to <span class="bold">{{ jacket.added_by.username }}</span>. Your
            contact information has been sent so that the user can contact you.
        </p>
    </div>
{% endblock %}

jacketswap/templates/jacket/create.html
{% extends "generic/base.html" %}

{% block title %}Add jacket &middot; JacketSwap{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <h5>Add a jacket</h5>
        <form class="form-vertical" action="{% url "jacket:create" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include "generic/form.html" %}
            <button type="submit" class="btn button-primary">Submit</button>
        </form>
    </div>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    {% load staticfiles %}
    <script src="{% static "generic/js/form.js" %}"></script>
{% endblock %}

jacketswap/templates/jacket/details.html
{% extends 'generic/base.html' %}
{% load staticfiles %}

{% block title %}{{ object.title }} &middot; JacketSwap{% endblock %}

{% block content %}
    <div class="container">
        <div class="row jacket-details">
            <div class="col-lg-9 jacket-info">
                <h5>
                    {% if object.returned %}
                        Returned:
                    {% else %}
                        {% if object.lost_found == 'lost' %}
                            Lost:
                        {% else %}
                            Found:
                        {% endif %}
                    {% endif %}
                    {{ object.title }}
                </h5>
                <div class="image" style="background-image: url({{ object.image.url }})"></div>
                <div class="image-zoom">
                    <img src="{{ object.image.url }}" />
                </div>
                <div class="description">{{ object.description }}</div>
            </div>
            <div class="col-lg-3 jacket-user">
                <h5>Added by</h5>
                <div class="user-image" style="background-image: url({% static 'generic/img/user-placeholder.jpg' %})"></div>
                <span class="user-fullname">
                    {% if object.added_by.get_full_name != '' %}
                        {{ object.added_by.get_full_name }}
                    {% else %}
                        Anonymous
                    {% endif %}
                </span>
                <br>
                <span class="user-username">{{ object.added_by.username }}</span>
            </div>
            <div class="col-lg-12">
                <form class="button-form" action="{% url 'jacket:claim' object.pk %}">
                    <button class="btn button-primary" {% if user.pk == object.added_by_id or object.returned %}disabled{% endif %} onclick="return confirm('By claiming this jacket, JacketSwap will send your e-mail address to the user that posted this jacket. Are you sure you want to continue?')">
                        {% if object.lost_found == 'lost' %}
                            I found this jacket!
                        {% else %}
                            This is my jacket!
                        {% endif %}
                    </button>
                </form>
                {% if object.added_by_id == user.id %}
                    <form class="button-form" action="{% url 'jacket:return' object.pk %}">
                        <button class="btn {% if not object.returned %}button-primary{% else %}button-secondary returned{% endif %}">
                            {% if not object.returned %}
                                Mark as returned
                            {% else %}
                                Returned!
                            {% endif %}
                        </button>
                    </form>
                {% endif %}
                {% if jacket.returned %}<span class="jacket-is-returned">This jacket is returned!</span>{% endif %}
            </div>
            <div class="col-lg-12 date">
                Added on {{ object.added_on }}
            </div>
        </div>
    </div>
{% endblock %}

jacketswap/templates/jacket/index.html
{% extends "generic/base.html" %}

{% block title %}
    {% if source == 'search' %}
        Search
    {% elif source == 'your-jackets' %}
        Jackets
    {% endif %} &middot; JacketSwap
{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <h5>
            {% if source == 'search' %}
                Search results
            {% elif source == 'your-jackets' %}
                Your jackets
            {% endif %}
        </h5>
        {% for jacket in jackets %}
            <a href="{% url 'jacket:details' jacket.pk %}">
                <div class="jacket-item {% if jacket.returned %}returned{% endif %}">
                    <div class="image" style="background-image: url({{ jacket.image.url }})"></div>
                    <div class="info">
                        <div class="title">{{ jacket.title }}</div>
                        <div class="location">{{ jacket.location }}</div>
                    </div>
                    <div class="lof">
                        {% if jacket.returned %}
                            Returned!
                        {% else %}
                            {{ jacket.lost_found }}
                        {% endif %}
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}